import type { Permission, Role } from './rbac.middleware.js';

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  STAFF: [
    'rooms:read',
    'reservations:read', 'reservations:create', 'reservations:edit',
    'reservations:checkIn', 'reservations:checkOut',
    'housekeeping:read', 'housekeeping:edit',
  ],
  MANAGER: [
    'rooms:read', 'rooms:create', 'rooms:edit', 'rooms:delete',
    'reservations:read', 'reservations:create', 'reservations:edit',
    'reservations:checkIn', 'reservations:checkOut', 'reservations:cancel',
    'reservations:delete',
    'invoices:read', 'invoices:create', 'invoices:edit', 'invoices:refund',
    'users:read', 'users:create', 'users:edit',
    'channels:read', 'channels:manage',
    'export:data',
  ],
  ADMIN: [
    'rooms:read', 'rooms:create', 'rooms:edit', 'rooms:delete',
    'reservations:read', 'reservations:create', 'reservations:edit',
    'reservations:checkIn', 'reservations:checkOut', 'reservations:cancel',
    'reservations:delete',
    'invoices:read', 'invoices:create', 'invoices:edit', 'invoices:refund', 'invoices:delete',
    'users:read', 'users:create', 'users:edit', 'users:delete',
    'housekeeping:read', 'housekeeping:edit',
    'channels:read', 'channels:manage',
    'billing:read', 'billing:manage',
    'audit:read',
    'settings:manage',
    'export:data',
  ],
  SUPER_ADMIN: [
    'rooms:read', 'rooms:create', 'rooms:edit', 'rooms:delete',
    'reservations:read', 'reservations:create', 'reservations:edit',
    'reservations:checkIn', 'reservations:checkOut', 'reservations:cancel',
    'reservations:delete',
    'invoices:read', 'invoices:create', 'invoices:edit', 'invoices:refund', 'invoices:delete',
    'users:read', 'users:create', 'users:edit', 'users:delete',
    'housekeeping:read', 'housekeeping:edit',
    'channels:read', 'channels:manage',
    'billing:read', 'billing:manage',
    'audit:read',
    'settings:manage',
    'export:data',
    'hotel:delete',
  ],
};
